#include "GuiFsm.h"
#include "GuiStateInit.h"
#include "GuiStateComComp.h"

constexpr EN_GUI_STATE GUI_STATE_ACTION_TABLE[EN_GUI_ACTION_NUM][EN_GUI_STATE_NUM] =
{
	/* EN_GUI_STATE_INIT	EN_GUI_STATE_COM_COMP	EN_GUI_STATE_START_WAIT		EN_GUI_STATE_IN_GAME_IDLE	EN_GUI_STATE_IN_GAME_BUSY	EN_GUI_STATE_GAME_RESULT*/
	/* EN_GUI_ACTION_COM_START_COMMP */	{EN_GUI_STATE_COM_COMP,	EN_GUI_STATE_COM_COMP,	EN_GUI_STATE_START_WAIT,	EN_GUI_STATE_IN_GAME_IDLE,	EN_GUI_STATE_IN_GAME_BUSY,	EN_GUI_STATE_GAME_RESULT	},
	/* EN_GUI_ACTION_GAME_START */		{EN_GUI_STATE_INIT,		EN_GUI_STATE_START_WAIT,EN_GUI_STATE_START_WAIT,	EN_GUI_STATE_START_WAIT,	EN_GUI_STATE_START_WAIT,	EN_GUI_STATE_START_WAIT		},
	/* EN_GUI_ACTION_GAME_START_COMP */	{EN_GUI_STATE_INIT,		EN_GUI_STATE_COM_COMP,	EN_GUI_STATE_IN_GAME_IDLE,	EN_GUI_STATE_IN_GAME_IDLE,	EN_GUI_STATE_IN_GAME_BUSY,	EN_GUI_STATE_GAME_RESULT	},
	/* EN_GUI_ACTION_PUT_DISC */		{EN_GUI_STATE_INIT,		EN_GUI_STATE_COM_COMP,	EN_GUI_STATE_START_WAIT,	EN_GUI_STATE_IN_GAME_BUSY,	EN_GUI_STATE_IN_GAME_BUSY,	EN_GUI_STATE_GAME_RESULT	},
	/* EN_GUI_ACTION_PUT_DISC_COMP */	{EN_GUI_STATE_INIT,		EN_GUI_STATE_COM_COMP,	EN_GUI_STATE_START_WAIT,	EN_GUI_STATE_IN_GAME_IDLE,	EN_GUI_STATE_IN_GAME_IDLE,	EN_GUI_STATE_GAME_RESULT	},
	/* EN_GUI_ACTION_GAME_END_COMP */	{EN_GUI_STATE_INIT,		EN_GUI_STATE_COM_COMP,	EN_GUI_STATE_START_WAIT,	EN_GUI_STATE_GAME_RESULT,	EN_GUI_STATE_GAME_RESULT,	EN_GUI_STATE_GAME_RESULT	},
};

GuiFsm::GuiFsm(void) :
	m_currentState(EN_GUI_STATE_INIT)
{
	m_actionList[EN_GUI_ACTION_COM_START_COMMP] = std::bind(&GuiFsm::ComStartComp, this);
	m_actionList[EN_GUI_ACTION_GAME_START] = std::bind(&GuiFsm::GameStart, this);
#if 0
	m_actionList[EN_GUI_ACTION_GAME_START_COMP] = std::bind(&GameStart, this);
	m_actionList[EN_GUI_ACTION_PUT_DISC] = std::bind(&GameStart, this);
	m_actionList[EN_GUI_ACTION_PUT_DISC_COMP] = std::bind(&GameStart, this);
	m_actionList[EN_GUI_ACTION_GAME_END_COMP] = std::bind(&GameStart, this);
#endif

	m_stateList[EN_GUI_STATE_INIT] = new GuiStateInit();
	m_stateList[EN_GUI_STATE_COM_COMP] = new GuiStateComComp();
}

void GuiFsm::DoAction(EN_GUI_ACTION enAction)
{
	m_actionList[enAction]();
	m_currentState = GUI_STATE_ACTION_TABLE[m_currentState][enAction];
}

void GuiFsm::ComStartComp(void)
{
	m_stateList[m_currentState]->ComStartComp();
}

void GuiFsm::GameStart(void)
{
	m_stateList[m_currentState]->GameStart();
}